version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-DBMS_PROJECT}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-sec_key}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_NAME:-DBMS_PROJECT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create_tables_fixed.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./inserting_data/complete_demo_data.sql:/docker-entrypoint-initdb.d/02-data.sql
    restart: unless-stopped

volumes:
  mysql_data:
