[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn main:app"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.9"
